# Generated by Django 3.0 on 2020-01-13 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Group name')),
                ('profile_photo', models.ImageField(upload_to='group_photo', verbose_name='Group_profile_photo')),
                ('short_desc', models.CharField(blank=True, max_length=60, verbose_name='short_description')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='add_datetime')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupsapp.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
