# Generated by Django 3.0.2 on 2020-02-16 15:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0003_auto_20200214_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='group_photo', verbose_name='Group_profile_photo'),
        ),
        migrations.AlterField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('12f950cd-dd5d-42f0-ab73-ec9f079fb0df'), verbose_name='uuid'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='task_name')),
                ('description', models.TextField(verbose_name='description')),
                ('is_done', models.BooleanField(default=False, verbose_name='is_done')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupsapp.Group')),
            ],
        ),
    ]
