# Generated by Django 3.0.2 on 2020-02-16 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0004_auto_20200216_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('050544f1-72d3-4575-859a-3ea07c7d3b5b'), verbose_name='uuid'),
        ),
    ]
