# Generated by Django 3.0.3 on 2020-02-16 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0005_auto_20200216_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('a3962a8e-0030-4b44-a024-088aae1ab3ab'), verbose_name='uuid'),
        ),
    ]
