# Generated by Django 3.0.3 on 2020-02-17 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0006_auto_20200216_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('f6181771-627c-4c5a-a52c-a092a7b9afdf'), verbose_name='uuid'),
        ),
    ]
