# Generated by Django 3.0.3 on 2020-02-20 08:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groupsapp', '0007_auto_20200217_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('1a920922-c806-492a-9da6-394e5b1cd85c'), verbose_name='uuid'),
        ),
    ]
