# Generated by Django 3.0.7 on 2020-06-18 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupsapp', '0009_auto_20200305_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('6b77d3b9-bdeb-412e-9d12-1e21a34c60cb'), verbose_name='uuid'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_creator', models.BooleanField(default=False, verbose_name='is_creator')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='is_moderator')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='add_datetime')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupsapp.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
