# Generated by Django 3.0.2 on 2020-02-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200214_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='user_photo', verbose_name='user_profile_photo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, verbose_name='user age'),
        ),
    ]
