# Generated by Django 3.0.3 on 2020-02-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20200216_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='whatsapp_url',
            new_name='facebook_url',
        ),
    ]
